// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service.proto

package checkout

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PurchaseRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PurchaseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseRequestMultiError, or nil if none found.
func (m *PurchaseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for User

	if len(errors) > 0 {
		return PurchaseRequestMultiError(errors)
	}

	return nil
}

// PurchaseRequestMultiError is an error wrapping multiple validation errors
// returned by PurchaseRequest.ValidateAll() if the designated constraints
// aren't met.
type PurchaseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseRequestMultiError) AllErrors() []error { return m }

// PurchaseRequestValidationError is the validation error returned by
// PurchaseRequest.Validate if the designated constraints aren't met.
type PurchaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseRequestValidationError) ErrorName() string { return "PurchaseRequestValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseRequestValidationError{}

// Validate checks the field values on PurchaseResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PurchaseResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseResponseMultiError, or nil if none found.
func (m *PurchaseResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	if len(errors) > 0 {
		return PurchaseResponseMultiError(errors)
	}

	return nil
}

// PurchaseResponseMultiError is an error wrapping multiple validation errors
// returned by PurchaseResponse.ValidateAll() if the designated constraints
// aren't met.
type PurchaseResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseResponseMultiError) AllErrors() []error { return m }

// PurchaseResponseValidationError is the validation error returned by
// PurchaseResponse.Validate if the designated constraints aren't met.
type PurchaseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseResponseValidationError) ErrorName() string { return "PurchaseResponseValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseResponseValidationError{}
